import Navbar from "@/components/navigation/navbar";
import ThemeProvider from "@/components/providers/theme-provider";
import type {Metadata} from "next";
import "./globals.css";

type RootLayoutProps = Readonly<{children: React.ReactNode}>;

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

function RootLayout({children}: RootLayoutProps) {
	return (
		<html lang="ru" suppressHydrationWarning>
			<body>
				<ThemeProvider>
					<Navbar />
					<main>
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}

export default RootLayout;
