import ThemeProvider from "@/components/theme-provider";
import {cn} from "@/lib/utils";
import type {Metadata} from "next";
import "./globals.css";
import {Playfair_Display, Roboto} from "next/font/google";

type RootLayoutProps = Readonly<{children: React.ReactNode}>;

const playfairDisplay = Playfair_Display({
	subsets: ["cyrillic", "latin"],
	variable: "--playfair-display"
});

const roboto = Roboto({
	weight: ["400", "500"],
	subsets: ["cyrillic", "latin"],
	variable: "--roboto"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

function RootLayout({children}: RootLayoutProps) {
	return (
		<html lang="en" className={cn(playfairDisplay.variable)} suppressHydrationWarning>
			<body className={roboto.className}>
				<ThemeProvider>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}

export default RootLayout;
