import ThemeProvider from "@/components/providers/theme-provider";
import {Toaster} from "@/components/ui/toaster";
import type {Metadata} from "next";
import "./globals.css";
import Script from "next/script";

type RootLayoutProps = Readonly<{children: React.ReactNode}>;

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



function RootLayout(props: RootLayoutProps) {
	return (
		<html lang="ru" suppressHydrationWarning>
			<Script src="http://localhost:8097" />
			<body>
				<ThemeProvider>
					{props.children}
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}

export default RootLayout;
